geom:
  id-generator: ${GEOM_ID_GENERATOR:UUID}

spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

logging:
  level:
    root: info
    io.github.xezzon: debug
